spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meeting
    username: root
    password: litianyu2002
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  servlet:
    context-path: /meeting
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*.xml